apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "0.10.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  install:
    crds: Create 
    remediation:
      retries: 3       
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3        
  values:
    installCRDs: true
    webhook:
      enabled: true
      readinessProbe:
        initialDelaySeconds: 60   
        periodSeconds: 10
        failureThreshold: 10      
    certController:
      enabled: true
      readinessProbe:
        initialDelaySeconds: 60   
        periodSeconds: 10
        failureThreshold: 10