apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deny-all.yaml
  - allow-gitea-from-traefik.yaml
  - allow-gitea-egress.yaml
  - allow-postgres-from-gitea.yaml
  - allow-redis-from-gitea.yaml
