apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-storage
  resources:
    requests:
      storage: 512Mi
